import type { FormEvent, ReactNode } from "react";
import { Alert, Button, Checkbox, TextField } from "../../src/components/ui";
import { AuthShell, ComposerCard, ErrorSummary, SocialContentCard, TopicHighlights } from "../../src/components/patterns";

export default { title: "Design System/Social and Auth", parameters: { layout: "fullscreen" } };
const Frame = ({ children, width = 720 }: { children: ReactNode; width?: number }) => <div dir="rtl" lang="ar" style={{ maxWidth: width, margin: "auto", padding: 24 }}>{children}</div>;

export const Login = () => <AuthShell title="تسجيل الدخول" description="انضم إلى معرفة موثوقة" trustPoints={["مصادر ظاهرة", "علماء موثقون", "خصوصيتك محترمة"]}><form onSubmit={(event: FormEvent) => event.preventDefault()}><TextField id="login-email" label="البريد الإلكتروني" autoComplete="email" /><TextField id="login-password" label="كلمة المرور" type="password" autoComplete="current-password" /><Checkbox id="remember" label="تذكرني على هذا الجهاز" /><Button type="submit">تسجيل الدخول</Button><Button type="button" variant="secondary">إنشاء حساب</Button></form></AuthShell>;
export const AuthErrors = () => <Frame width={520}><div className="ds-stack"><ErrorSummary items={[{ id: "register-email", label: "أدخل بريدًا صالحًا" }, { id: "register-password", label: "استخدم 12 محرفًا على الأقل" }]} /><TextField id="register-email" label="البريد الإلكتروني" error="أدخل بريدًا صالحًا" /><TextField id="register-password" label="كلمة المرور" type="password" error="استخدم 12 محرفًا على الأقل" /><Button loading>إنشاء حساب عضو</Button></div></Frame>;
export const FeedPatterns = () => <Frame><div className="ds-stack"><TopicHighlights items={[{ id: "fiqh", label: "الفقه", meta: "مختارات" }, { id: "seerah", label: "السيرة" }, { id: "family", label: "الأسرة" }]} activeId="fiqh" /><ComposerCard author={<strong>محمد مبارك</strong>} label="مساهمة جديدة" placeholder="ما المسألة التي تريد فهمها؟" privacyControl={<span>عام</span>} /><SocialContentCard id="post-1" author={<strong>د. عبد الرحمن · موثّق</strong>} meta={<time dateTime="2026-08-22">منذ ساعتين</time>} title="كيف نفهم اختلاف الفقهاء؟" citation={<span>المصدر [1] · مدخل إلى أصول الفقه</span>} commentAction={<Button variant="ghost">تعقيب</Button>}><p>مدخل موجز يضع المصادر والسياق قبل أرقام التفاعل.</p></SocialContentCard></div></Frame>;
export const States = () => <Frame width={520}><div className="ds-stack"><Alert tone="success" title="تم الحفظ">أصبحت المادة في محفوظاتك.</Alert><Alert tone="error" title="تعذر الإرسال">احتفظنا بالمسودة. أعد المحاولة عند عودة الاتصال.</Alert><Button disabled>إجراء غير متاح</Button></div></Frame>;
