"use client";
import { useState, type FormEvent } from "react";
import type { Question, QuestionVisibility, Source } from "@/domain";
import { Button, TextField } from "@/components/ui";
import { AsyncAction, OpinionGroup, SourceCitation, StatusTimeline, type AsyncActionState } from "@/components/patterns";
import { FeatureState, type FeatureStatus } from "../shared/FeatureState";

export interface QuestionDraft { title: string; details: string; specialtyId: string; visibility: QuestionVisibility }
export function AskQuestion({ status = "ready", onSubmit }: { status?: FeatureStatus; onSubmit?: (draft: QuestionDraft) => void }) { const [visibility, setVisibility] = useState<QuestionVisibility>("public"); function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const d = new FormData(e.currentTarget); onSubmit?.({ title: String(d.get("title") ?? ""), details: String(d.get("details") ?? ""), specialtyId: String(d.get("specialty") ?? ""), visibility }); } return <FeatureState status={status}><form aria-labelledby="ask-title" onSubmit={submit}><h1 id="ask-title">اطرح سؤالًا</h1><TextField id="question-title" name="title" label="عنوان السؤال" required /><label htmlFor="question-details">التفاصيل</label><textarea id="question-details" name="details" required /><TextField id="question-specialty" name="specialty" label="التخصص" required /><fieldset><legend>من يمكنه رؤية السؤال؟</legend><label><input type="radio" checked={visibility === "public"} onChange={() => setVisibility("public")} />عام</label><label><input type="radio" checked={visibility === "private"} onChange={() => setVisibility("private")} />خاص</label></fieldset><aside role="note">{visibility === "public" ? "سيظهر السؤال وإجاباته للعامة وقد يظهران في نتائج البحث." : "سيراه أنت والمختصون المكلفون فقط، ولن يظهر في البحث أو المشاركة."}<br />لا تضف اسمًا أو رقمًا أو بيانات تعريفية لا يحتاجها المختص.</aside><Button type="submit">إرسال السؤال للمراجعة</Button></form></FeatureState>; }

export function QuestionDetail({ question, privateAccess = true, sources = [] }: { question: Question; privateAccess?: boolean; sources?: readonly Source[] }) { if (question.visibility === "private" && !privateAccess) return <FeatureState status="privacy"><span /></FeatureState>; return <article aria-labelledby="question-title"><p>{question.visibility === "private" ? "سؤال خاص" : "سؤال عام"}</p><h1 id="question-title">{question.title}</h1><p>{question.details}</p><StatusTimeline items={[{ id: "current", status: question.status, description: "الحالة الحالية للسؤال", timestamp: "2026-08-22" }]} />{sources.length > 0 && <OpinionGroup id="opinion-1" label="عرض موثق" summary="في هذه المسألة آراء معتبرة موثقة بالمصادر." evidence={sources.map((s, i) => <SourceCitation key={s.id} index={i + 1} type={s.type} title={s.title} />)} />}</article>; }

export function AnswerEditor({ permission = true, state = "idle", onSubmit }: { permission?: boolean; state?: AsyncActionState; onSubmit?: (answer: string) => void }) { const [answer, setAnswer] = useState(""); if (!permission) return <FeatureState status="permission"><span /></FeatureState>; return <section aria-labelledby="answer-title"><h1 id="answer-title">صياغة الإجابة</h1><label htmlFor="answer-body">الإجابة الموثقة</label><textarea id="answer-body" value={answer} onChange={e => setAnswer(e.currentTarget.value)} /><p>يلزم مصدر واحد على الأقل قبل الإرسال.</p><AsyncAction state={state} label="إرسال للمراجعة" {...(state === "uncertain" ? { message: "لم نتمكن من تأكيد النتيجة. تحقق من الحالة قبل إعادة الإرسال." } : {})} onAction={() => onSubmit?.(answer)} /></section>; }
